### PR TITLE
edit on heating_map.vtk creation

### PR DESCRIPTION
**Pull request by davidepettinari**

### CODE REVIEW

**Comment by shimwell** [comment]
Much appreciated. Thanks for reporting and double thanks for fixing

**Comment by davidepettinari** [comment]
You're welcome.
Can I ask you a question? I noticed that in the proposed example the tally 'heating' was used.
I am doing a neutronic analysis where I have to calculate the fusion power from neutrons and using the 'heating' tally I do not get the desired result, but I get a lower power value.
In my analysis I implemented a plasma source like the one proposed in the file '2_run_openmc_dagmc_simulation.py' and I noticed that by entering: “ my_source.particle = 'photon' ” I get the correct result instead.
It seems that the program is able to consider all interactions with photons, while losing some with neutrons. Could you explain me why?
Thanks again and sorry for the trouble.
Best regards.
Davide

Da: Jonathan Shimwell ***@***.***>
Inviato: martedì 14 marzo 2023 19:24
A: fusion-energy/magnetic_fusion_openmc_dagmc_paramak_example ***@***.***>
Cc: Davide Pettinari ***@***.***>; Author ***@***.***>
Oggetto: Re: [fusion-energy/magnetic_fusion_openmc_dagmc_paramak_example] edit on heating_map.vtk creation (PR #12)


Much appreciated. Thanks for reporting and double thanks for fixing

**Comment by shimwell** [comment]
That is strange, have you modified the script from the example. If so feel free to post it here and I can take a look.

The only other thing I can think of is which cross sections are you using.

**Comment by davidepettinari** [comment]
> That is strange, have you modified the script from the example. If so feel free to post it here and I can take a look.
> 
> The only other thing I can think of is which cross sections are you using.

I noticed this in another code I wrote, but you can easily see it in this one as well. 
Preface: I did not modify the script and I did not change the cross sections.
Running the script the results are:
- TBR = 0.42
- Heating of 16.45110774967452 MeV per source particle is deposited. 
This heating value corresponds to a source of 4.11 MeV and not 14.08 MeV as it is defined.

Now, Inserting in the script '2_run_openmc_dagmc_simulation.py' the following change: `my_source.particle = 'photon'`.
The results obtained are:
- TBR = 0 (and this is correct since photons are simulated)
- Heating of 56.31 MeV per source particle is deposited.
This second result is also correct since it corresponds to a source of 14.08 MeV.
Why the difference in results?

**Pull request merged**
